# Generated by Django 3.2.4 on 2022-12-02 15:39

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='слэг')),
                ('weight', models.IntegerField(default=100, validators=[catalog.validators.validate_number], verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='слэг')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('text', tinymce.models.HTMLField(validators=[catalog.validators.Validate_amazing('превосходно', 'роскошно')], verbose_name='текст')),
                ('photo', models.ImageField(default='img/defaultphoto.jpg', upload_to='uploads/%Y/%m/%d/', verbose_name='превью')),
                ('is_on_main', models.BooleanField(default=False, verbose_name='флаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категории')),
                ('tag', models.ManyToManyField(to='catalog.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='фото')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='галерея')),
            ],
            options={
                'verbose_name': 'галерея фотографии',
                'verbose_name_plural': 'галерея фотографии',
            },
        ),
    ]
