# Generated by Django 3.2 on 2022-11-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainphoto',
            old_name='thumbnail',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.mainphoto'),
        ),
    ]
