# Generated by Django 4.1.2 on 2022-10-31 08:58

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_item_category_catalog_item_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog_category',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='catalog_category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catalog_item',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='catalog_item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catalog_tag',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='catalog_tag',
            name='name',
        ),
        migrations.AlterField(
            model_name='catalog_category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[catalog.validators.validate_word]),
        ),
        migrations.AlterField(
            model_name='catalog_tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[catalog.validators.validate_word]),
        ),
    ]
