# Generated by Django 3.2 on 2022-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221109_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='img/defaultphoto.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
