# Generated by Django 4.1.2 on 2022-10-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_catalog_category_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog_category',
            options={'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='catalog_item',
            options={'verbose_name': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='catalog_tag',
            options={'verbose_name': 'Тэги'},
        ),
    ]
