# Generated by Django 3.2 on 2022-11-10 18:42

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221110_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(validators=[catalog.validators.Validate_amazing('превосходно', 'роскошно')], verbose_name='текст'),
        ),
    ]
