# Generated by Django 4.1.2 on 2022-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalog_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog_category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='catalog_item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='catalog_tag',
            options={'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
        migrations.AddField(
            model_name='catalog_category',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalog_category',
            name='name',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog_item',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalog_item',
            name='name',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog_tag',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalog_tag',
            name='name',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
