# Generated by Django 4.1.2 on 2022-11-01 06:49

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_catalog_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField(validators=[catalog.validators.Validate_amazing])),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.RenameModel(
            old_name='catalog_category',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Catalog_tag',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='Catalog_item',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(to='catalog.tag', verbose_name='теги'),
        ),
    ]
