# Generated by Django 3.2.4 on 2022-12-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким ником уже есть'}, max_length=150),
        ),
        migrations.DeleteModel(
            name='Birthday',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
